import type { Form } from "@/types/form";

export const demoForm: Form = {
  id: "demo-1",
  userId: "user-1",
  title: "Product Feedback Survey",
  slug: "product-feedback",
  isPublished: true,
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  welcomeScreen: {
    title: "We'd love your feedback",
    description:
      "Help us build a better product. This survey takes about 2 minutes to complete. Your responses are anonymous.",
    buttonText: "Start",
  },
  thankYouScreen: {
    title: "Thank you!",
    description:
      "Your feedback means the world to us. We'll use it to make our product even better.",
  },
  questions: [
    {
      id: "q1",
      type: "short_text",
      title: "What's your name?",
      description: "We'd love to know who we're talking to.",
      placeholder: "Jane Doe",
      required: false,
    },
    {
      id: "q2",
      type: "email",
      title: "What's your email address?",
      description: "We'll only use this to follow up if needed.",
      required: true,
    },
    {
      id: "q3",
      type: "multiple_choice",
      title: "How did you hear about us?",
      required: true,
      choices: [
        { id: "c1", label: "Search engine (Google, Bing)", value: "search" },
        { id: "c2", label: "Social media", value: "social" },
        { id: "c3", label: "Friend or colleague", value: "referral" },
        { id: "c4", label: "Blog or article", value: "blog" },
        { id: "c5", label: "Other", value: "other" },
      ],
    },
    {
      id: "q4",
      type: "rating",
      title: "How likely are you to recommend us to a friend?",
      description: "On a scale of 0-10",
      required: true,
      min: 0,
      max: 10,
    },
    {
      id: "q5",
      type: "star_rating",
      title: "How would you rate your overall experience?",
      required: true,
      max: 5,
    },
    {
      id: "q6",
      type: "yes_no",
      title: "Have you used a similar product before?",
      required: true,
    },
    {
      id: "q7",
      type: "checkboxes",
      title: "Which features do you use the most?",
      description: "Select all that apply.",
      required: true,
      choices: [
        { id: "f1", label: "Dashboard", value: "dashboard" },
        { id: "f2", label: "Analytics", value: "analytics" },
        { id: "f3", label: "Reporting", value: "reporting" },
        { id: "f4", label: "Integrations", value: "integrations" },
        { id: "f5", label: "API", value: "api" },
      ],
    },
    {
      id: "q8",
      type: "dropdown",
      title: "What's your role?",
      required: true,
      choices: [
        { id: "r1", label: "Designer", value: "designer" },
        { id: "r2", label: "Developer", value: "developer" },
        { id: "r3", label: "Product Manager", value: "pm" },
        { id: "r4", label: "Marketing", value: "marketing" },
        { id: "r5", label: "Executive", value: "executive" },
        { id: "r6", label: "Other", value: "other" },
      ],
    },
    {
      id: "q9",
      type: "number",
      title: "How many people are on your team?",
      placeholder: "e.g. 12",
      required: false,
      min: 1,
      max: 10000,
    },
    {
      id: "q10",
      type: "date",
      title: "When did you start using our product?",
      required: false,
    },
    {
      id: "q11",
      type: "statement",
      title: "Great progress! Just a couple more questions.",
      description: "We really appreciate you taking the time to share your thoughts.",
      required: false,
    },
    {
      id: "q12",
      type: "long_text",
      title: "What's one thing we could do better?",
      description: "Be as specific as you'd like. We read every response.",
      placeholder: "I wish you would...",
      required: false,
    },
    {
      id: "q13",
      type: "file_upload",
      title: "Have a screenshot to share?",
      description: "Upload any images that help illustrate your feedback.",
      required: false,
      maxFileSize: 5,
      acceptedFileTypes: [".png", ".jpg", ".jpeg", ".gif", ".webp"],
    },
  ],
};
